# Generated by Django 2.2.4 on 2022-06-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_and_Registration_App', '0002_remove_users_confirm_pw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Fname',
            new_name='firest_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Password',
            new_name='password',
        ),
    ]
